name: Build APK

on:
  workflow_dispatch: {}
  push:
    tags:
      - "v*"

jobs:
  android:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest
      options: --user root
    steps:
      - uses: actions/checkout@v4

      - name: Cache .buildozer and .gradle
        uses: actions/cache@v4
        with:
          path: |
            .buildozer
            ~/.gradle
          key: buildozer-${{ runner.os }}-${{ hashFiles(buildozer.spec) }}

      - name: Build debug APK
        env:
          BUILDOZER_WARN_ON_ROOT: "0"
        run: |
          buildozer -v android debug

      - name: Rename APK artifact
        run: |
          mkdir -p artifacts
          apk_file=$(ls -1 bin/*.apk | head -n1)
          cp "$apk_file" "artifacts/vision-$(date +%Y%m%d%H%M)-debug.apk"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: vision-apk
          path: artifacts/*.apk

      - name: Create GitHub Release (on tag)
        if: startsWith(github.ref, refs/tags/v)
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*.apk
          generate_release_notes: true
